### ISSUE TITLE
请问train_flist里是原始图片还是带有masked的图片

### ISSUE THREAD

**Issue by XiaxiaYan** [BaoGevvvv5/photo-restoration#1]

**Comment by BaoGevvvv5** [comment]
图像修复的网络里面训练集用的是原始图片

**Comment by XiaxiaYan** [comment]
> 图像修复的网络里面训练集用的是原始图片
万分感谢您的及时回复， 如果我数据集图片分辨率是512*512， 那么在训练时设置random_crop: True, 对于小的mask在测试时是否会结果有影响

**Comment by BaoGevvvv5** [comment]
我个人认为不会有太大影响（我没有尝试过裁剪）。不过在我之前的测试里面这个网络对于很小的mask（占图像大小小于5%）来说修复效果都比较好。这个网络尤其是对小的mask修复效果很好，例如一些噪点的修复，但是大块图像丢失修复效果就较差，不过总的来说还是跟训练有关，训练的好（比如batchsize足够大，训练集数量足够多）修复效果都会提升很多。

**Comment by BaoGevvvv5** [comment]
这一部分代码我大部分是来自于generative image inpainting，你可以参考一下这个代码库https://github.com/JiahuiYu/generative_inpainting。
我只是当时看到一篇有意思的关于旧照片修复的blog想试试所以随便找了个修复论文拉下来做了个小demo，最后和u-net整合在一起做了一个小项目。

**Comment by XiaxiaYan** [comment]
> 我个人认为不会有太大影响（我没有尝试过裁剪）。不过在我之前的测试里面这个网络对于很小的mask（占图像大小小于5%）来说修复效果都比较好。这个网络尤其是对小的mask修复效果很好，例如一些噪点的修复，但是大块图像丢失修复效果就较差，不过总的来说还是跟训练有关，训练的好（比如batchsize足够大，训练集数量足够多）修复效果都会提升很多。
万分感谢，我现在训练了6000张数据集，跑了6个小时，刚迭代到28000，与您推荐的200000还差很远

**Comment by XiaxiaYan** [comment]
> 我个人认为不会有太大影响（我没有尝试过裁剪）。不过在我之前的测试里面这个网络对于很小的mask（占图像大小小于5%）来说修复效果都比较好。这个网络尤其是对小的mask修复效果很好，例如一些噪点的修复，但是大块图像丢失修复效果就较差，不过总的来说还是跟训练有关，训练的好（比如batchsize足够大，训练集数量足够多）修复效果都会提升很多。

inpaint.yml文件中，除了data的存储位置外，其他是不是都可以按您的数据配置？

**Comment by XiaxiaYan** [comment]
最近刚开始看图像修复相关方向，您的程序真的帮助很多，再次感谢

**Comment by BaoGevvvv5** [comment]
大部分都应该不用改。有一些可以按照自己的情况来配置，例如batch_size，我当时只有一块2060s，6张就是我的显存极限了，如果你有更好的显卡，大一些的batch_size当然能有更好的效果。

**Comment by BaoGevvvv5** [comment]
> 最近刚开始看图像修复相关方向，您的程序真的帮助很多，再次感谢

没事，请继续加油。不过我自己已经没有再做这个方向，而是转开发了。

**Comment by XiaxiaYan** [comment]
> 大部分都应该不用改。有一些可以按照自己的情况来配置，例如batch_size，我当时只有一块2060s，6张就是我的显存极限了，如果你有更好的显卡，大一些的batch_size当然能有更好的效果。

**Comment by XiaxiaYan** [comment]
> > 最近刚开始看图像修复相关方向，您的程序真的帮助很多，再次感谢
> 
> 没事，请继续加油。不过我自己已经没有再做这个方向，而是转开发了。

谢谢您的帮助，祝工作顺利
